language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run docs:build"

deploy:
  provider: pages:git
  edge: true
  local_dir: dist-docs
  on:
    branch: master
